<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "adv_education".
 *
 * @property integer $id
 * @property integer $adv_id
 * @property string $school
 * @property string $degree
 * @property string $major
 * @property integer $start_time
 * @property integer $end_time
 * @property string $grade
 * @property string $school_activity
 * @property string $achievement
 * @property integer $create_time
 * @property integer $update_time
 *
 * @property Advertiser $adv
 */
class AdvEducation extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'adv_education';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['adv_id'], 'required'],
            [['adv_id', 'start_time', 'end_time', 'create_time', 'update_time'], 'integer'],
            [['school_activity', 'achievement'], 'string'],
            [['school', 'degree', 'major', 'grade'], 'string', 'max' => 255],
            [['adv_id'], 'exist', 'skipOnError' => true, 'targetClass' => Advertiser::className(), 'targetAttribute' => ['adv_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'adv_id' => 'Adv ID',
            'school' => 'School',
            'degree' => 'Degree',
            'major' => 'Major',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'grade' => 'Grade',
            'school_activity' => 'School Activity',
            'achievement' => 'Achievement',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdv()
    {
        return $this->hasOne(Advertiser::className(), ['id' => 'adv_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->create_time = time();
            $this->update_time = time();
        } else {
            $this->update_time = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        $adv = $this->adv;
        $adv->setProfileComplete();
        $adv->save();
    }


}
