<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "adv_experience".
 *
 * @property integer $id
 * @property integer $adv_id
 * @property string $title
 * @property string $company
 * @property string $address
 * @property integer $start_time
 * @property integer $end_time
 * @property string $content
 * @property integer $create_time
 * @property integer $update_time
 *
 * @property Advertiser $adv
 */
class AdvExperience extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'adv_experience';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
//            [['adv_id'], 'required'],
            [['adv_id', 'start_time', 'end_time', 'create_time', 'update_time'], 'integer'],
            [['content'], 'string'],
            [['title', 'company', 'address'], 'string', 'max' => 255],
            [['adv_id'], 'exist', 'skipOnError' => true, 'targetClass' => Advertiser::className(), 'targetAttribute' => ['adv_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'adv_id' => 'Adv ID',
            'title' => 'Title',
            'company' => 'Company',
            'address' => 'Address',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'content' => 'Content',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdv()
    {
        return $this->hasOne(Advertiser::className(), ['id' => 'adv_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->create_time = time();
            $this->update_time = time();
        } else {
            $this->update_time = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
